# kNN - k Nearest Neighbors - k Vizinhos mais próximos

## Importação de módulos python


In [1]:
import sklearn
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

## Carregamento dos dados como dicionário Python


In [2]:
dados = datasets.load_iris()

In [3]:
dados.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [4]:
print(dados['target_names'])

['setosa' 'versicolor' 'virginica']


## Carregamento dos dados como matriz X de features e vetor y de rótulos 

In [5]:
X, y = datasets.load_iris(return_X_y=True)

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
X.shape

(150, 4)

In [8]:
y.shape

(150,)

In [9]:
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [10]:
y[0]

0

## Separação entre conjunto de treino e conjunto de teste

In [11]:
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.9, random_state=42, stratify=y)

In [12]:
y_treino

array([1, 1, 0, 1, 0, 2, 0, 2, 1, 0, 1, 0, 2, 2, 2])

In [13]:
y_teste

array([0, 0, 0, 0, 1, 0, 1, 2, 0, 2, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 2, 1,
       1, 2, 1, 2, 1, 2, 0, 2, 1, 0, 2, 1, 1, 2, 1, 1, 0, 2, 0, 0, 0, 2,
       1, 1, 1, 0, 2, 0, 0, 0, 2, 0, 2, 1, 1, 1, 0, 1, 0, 1, 1, 0, 2, 1,
       0, 0, 2, 0, 0, 2, 1, 1, 2, 2, 2, 2, 1, 2, 0, 2, 1, 1, 1, 2, 1, 1,
       2, 0, 0, 0, 2, 1, 2, 1, 1, 2, 0, 1, 1, 0, 2, 1, 2, 0, 2, 0, 2, 1,
       1, 2, 0, 2, 1, 2, 2, 0, 0, 2, 2, 2, 1, 2, 2, 2, 1, 1, 0, 1, 0, 2,
       2, 0, 2])

In [14]:
y_treino.shape

(15,)

In [15]:
y_teste.shape

(135,)

In [16]:
np.sum(y_treino == 0), np.sum(y_treino == 1), np.sum(y_treino == 2)

(5, 5, 5)

In [17]:
np.sum(y_teste == 0), np.sum(y_teste == 1), np.sum(y_teste == 2)

(45, 45, 45)

In [18]:
X[0], y[0]

(array([5.1, 3.5, 1.4, 0.2]), 0)

## Instanciação do modelo kNN

In [19]:
modelo = KNeighborsClassifier(n_neighbors=5)

## Treinamento do modelo usando os dados de treino

In [20]:
modelo.fit(X_treino, y_treino)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

## Usando o modelo treinado para predizer os rótulos a partir dos dados de teste (X_test)

In [21]:
y_pred = modelo.predict(X_teste)

In [22]:
y_pred

array([0, 0, 0, 0, 1, 0, 1, 2, 0, 2, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 2, 1,
       1, 1, 1, 2, 1, 2, 0, 2, 1, 0, 2, 1, 1, 2, 1, 1, 0, 2, 0, 0, 0, 2,
       1, 1, 1, 0, 2, 0, 0, 0, 2, 0, 2, 1, 2, 1, 0, 1, 0, 1, 1, 0, 2, 2,
       0, 0, 2, 0, 0, 2, 1, 1, 2, 2, 1, 1, 1, 2, 0, 1, 1, 1, 1, 2, 1, 1,
       1, 0, 0, 0, 2, 1, 2, 1, 1, 1, 0, 1, 1, 0, 2, 1, 2, 0, 2, 0, 1, 1,
       1, 1, 0, 2, 1, 2, 1, 0, 0, 2, 1, 2, 1, 2, 2, 2, 1, 1, 0, 1, 0, 2,
       2, 0, 2])

In [23]:
y_teste

array([0, 0, 0, 0, 1, 0, 1, 2, 0, 2, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 2, 1,
       1, 2, 1, 2, 1, 2, 0, 2, 1, 0, 2, 1, 1, 2, 1, 1, 0, 2, 0, 0, 0, 2,
       1, 1, 1, 0, 2, 0, 0, 0, 2, 0, 2, 1, 1, 1, 0, 1, 0, 1, 1, 0, 2, 1,
       0, 0, 2, 0, 0, 2, 1, 1, 2, 2, 2, 2, 1, 2, 0, 2, 1, 1, 1, 2, 1, 1,
       2, 0, 0, 0, 2, 1, 2, 1, 1, 2, 0, 1, 1, 0, 2, 1, 2, 0, 2, 0, 2, 1,
       1, 2, 0, 2, 1, 2, 2, 0, 0, 2, 2, 2, 1, 2, 2, 2, 1, 1, 0, 1, 0, 2,
       2, 0, 2])

## Calculando e mostrando o percentual de acertos (acurácia)

In [24]:
qdt_acertos = np.sum(y_pred == y_teste)
qdt_total_de_elementos = y_teste.shape[0]
print('acurácia de {}%'.format(qdt_acertos / qdt_total_de_elementos * 100))

acurácia de 91.11111111111111%
