# Autor: Natan Nobre Chaves
## kNN Regression

### 1. Altere nossa implementação de kNN para que ela possa calcular regressão. Dica: crie uma função predict_regression baseada na função predict_classification do documento notebook 02-Aula kNN.ipynb.

In [2]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor

In [3]:
def euclidean_distances(X, X_row):
    X_ = (X - X_row) ** 2
    return np.sum(X_, axis=1) ** 0.5

In [4]:
def get_neighbors(X_train, test_row, k):
    distances = euclidean_distances(X_train, test_row)
    idx_sort = np.argsort(distances)
    return idx_sort[:k]

In [5]:
def predict_regression(X, y, test_row, k):
    idx_sort = get_neighbors(X, test_row, k)
    output_values = y[idx_sort]
    return (np.mean(output_values))

### 2. Use os seguintes dados como dados de treino (X_treino) para o kNN, onde House Price Index é o nosso rótulo (label ou y_treino)

In [6]:
dict_house_price = {"Age":[25, 35, 45, 20, 35, 52, 23, 40, 60, 48, 33],
                    "Loan":[40000, 60000, 80000, 20000, 120000, 18000, 95000,                                                               62000, 100000, 220000, 150000],
                    "House Price Index":[135, 256, 231, 267, 139, 150,                                                                                    127, 216, 139, 250, 264]}
house_price = pd.DataFrame(dict_house_price)
house_price                    

Age    Loan  House Price Index
0    25   40000                135
1    35   60000                256
2    45   80000                231
3    20   20000                267
4    35  120000                139
5    52   18000                150
6    23   95000                127
7    40   62000                216
8    60  100000                139
9    48  220000                250
10   33  150000                264

In [7]:
X_train = house_price[["Age", "Loan"]].values
X_train

array([[    25,  40000],
       [    35,  60000],
       [    45,  80000],
       [    20,  20000],
       [    35, 120000],
       [    52,  18000],
       [    23,  95000],
       [    40,  62000],
       [    60, 100000],
       [    48, 220000],
       [    33, 150000]], dtype=int64)

In [8]:
y_train = house_price["House Price Index"].values
y_train

array([135, 256, 231, 267, 139, 150, 127, 216, 139, 250, 264], dtype=int64)

#### a) Calcular o rótulo para quando Age = 42 e Loan = $142,000.

In [9]:
aX_test = np.array([42, 142000])

In [10]:
k = 3
print('Rotulo Predito: {}'.format(predict_regression(X_train, y_train, aX_test, k)))

Rotulo Predito: 180.66666666666666


#### b) Calcular o rótulo para quando Age = 30 e Loan = $50,000.

In [11]:
bX_test = np.array([30, 50000])

In [12]:
k = 3
print('Rotulo Predito: {}'.format(predict_regression(X_train, y_train, bX_test, k)))

Rotulo Predito: 202.33333333333334


### 3. O conjunto de dados de qualidade de vinho consiste na predição da qualidade de vinhos brancos sobre uma escala dada medições químicas de cada vinho. Baixe o conjunto de qualidade de vinho e faça o seguinte com ele em um Jupyter Notebook:

In [13]:
wine = pd.read_csv("datasets/winequality-white.csv", delimiter=';')
wine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

### 3.1. Separe 70% dos dados para treino (conjunto de treino) e 30% dos dados para teste (conjunto de teste).

In [14]:
y = wine['quality'].values
print(y)

[6 6 6 ... 6 7 6]


In [15]:
X = wine
del X['quality']
X = X.values
X

array([[ 7.  ,  0.27,  0.36, ...,  3.  ,  0.45,  8.8 ],
       [ 6.3 ,  0.3 ,  0.34, ...,  3.3 ,  0.49,  9.5 ],
       [ 8.1 ,  0.28,  0.4 , ...,  3.26,  0.44, 10.1 ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  2.99,  0.46,  9.4 ],
       [ 5.5 ,  0.29,  0.3 , ...,  3.34,  0.38, 12.8 ],
       [ 6.  ,  0.21,  0.38, ...,  3.26,  0.32, 11.8 ]])

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=42, stratify=y)

In [17]:
print(wine.shape)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(4898, 11)
(3428, 11)
(1470, 11)
(3428,)
(1470,)


### 3.2. Crie um modelo de regressão de qualidade de vinho usando o kNN para k=5.
### 3.3. Use o modelo de regressão sobre X_test para calcular os valores preditos dos rótulos (y_pred).

In [18]:
k = 5
kNNr_model = KNeighborsRegressor(n_neighbors=k)
kNNr_model.fit(X_train, y_train)
y_pred = kNNr_model.predict(X_test)
print(y_pred)

[6.4 6.4 6.4 ... 5.6 6.4 6.2]
