 ## 1. Resolver a classificação do Iris dataset para k=3 e k=5 com essas funções que implementamos no documento colab. Usando 70% dos dados para treino e 30% para teste. Ou seja: não é para usar a implementação do scikit para o kNN, nem o split_train_test do scikit.

In [466]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [467]:
# reading iris dataset
iris = pd.read_csv("dataset/iris.csv", index_col=0)
print(iris.head())
print(iris.shape)

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id                                                                       
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa
(150, 5)


In [468]:
# separated by species
type_setosa = iris[iris["Species"] == "Iris-setosa"]
type_virginica = iris[iris["Species"] == "Iris-virginica"]
type_versicolor = iris[iris["Species"] == "Iris-versicolor"]
# number of observations
print("Iris-setosa: " + str(type_setosa.shape[0]) + " amostras")
print("Iris-virginica: " + str(type_virginica.shape[0]) + " amostras")
print("Iris-versicolor: " + str(type_versicolor.shape[0]) + " amostras")
print(type_setosa)

Iris-setosa: 50 amostras
Iris-virginica: 50 amostras
Iris-versicolor: 50 amostras
    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id                                                                       
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa
6             5.4           3.9            1.7           0.4  Iris-setosa
7             4.6           3.4            1.4           0.3  Iris-setosa
8             5.0           3.4            1.5           0.2  Iris-setosa
9             4.4           2.9            1.4           0.2  Iris-setosa
10            4.9           3.1            1.5           0.1  Iris-setosa
11            5.4           3.

In [469]:
# All classes are shuffled
type_setosa = type_setosa.sample(frac=1)
type_versicolor = type_versicolor.sample(frac=1)
type_virginica = type_virginica.sample(frac=1)

# Classes concatenated to create train data and test data
train_data = pd.concat([type_setosa[:int(type_setosa.shape[0]*0.7)], type_versicolor[:int(type_versicolor.shape[0]*0.7)], type_virginica[:int(type_virginica.shape[0]*0.7)]])
print(train_data)
test_data = pd.concat([type_setosa[int(type_setosa.shape[0]*0.7):], type_versicolor[int(type_versicolor.shape[0]*0.7):], type_virginica[int(type_virginica.shape[0]*0.7):]])

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id                                                                           
46             4.8           3.0            1.4           0.3     Iris-setosa
41             5.0           3.5            1.3           0.3     Iris-setosa
33             5.2           4.1            1.5           0.1     Iris-setosa
39             4.4           3.0            1.3           0.2     Iris-setosa
26             5.0           3.0            1.6           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
113            6.8           3.0            5.5           2.1  Iris-virginica
127            6.2           2.8            4.8           1.8  Iris-virginica
104            6.3           2.9            5.6           1.8  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
116            6.4           3.2            5.3           2.3  I

In [470]:
print(test_data.shape)
print(train_data.shape)
print(train_data)

(45, 5)
(105, 5)
     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id                                                                           
46             4.8           3.0            1.4           0.3     Iris-setosa
41             5.0           3.5            1.3           0.3     Iris-setosa
33             5.2           4.1            1.5           0.1     Iris-setosa
39             4.4           3.0            1.3           0.2     Iris-setosa
26             5.0           3.0            1.6           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
113            6.8           3.0            5.5           2.1  Iris-virginica
127            6.2           2.8            4.8           1.8  Iris-virginica
104            6.3           2.9            5.6           1.8  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
116            6.4           3.2            5.3

In [471]:
def euclidean_distances(X, X_row):
    X_ = (X - X_row) ** 2
    return np.sum(X_, axis=1) ** 0.5

In [472]:
def get_neighbors(X_train, test_row, k):
    distances = euclidean_distances(X_train, test_row)
    idx_sort = np.argsort(distances)
    return idx_sort[:k]

In [473]:
def predict_classification(X, y, test_row, k):
    idx_sort = get_neighbors(X, test_row, k)
    output_values = y[idx_sort]
    counts = np.unique(output_values, return_counts=True)
    idx_max = np.argmax(counts[1])
    prediction = counts[0][idx_max]
    #print('idx_sort:{}, output_values:{}, prediction:{}'.format(idx_sort, output_values, prediction))
    return prediction

In [474]:
# Formating the data to fit on the functions above
y_train = train_data['Species'].values
X_train = train_data
del X_train['Species']
X_train = X_train.values

In [475]:
print(X_train)
print(y_train)

[[4.8 3.  1.4 0.3]
 [5.  3.5 1.3 0.3]
 [5.2 4.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.  3.  1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [4.8 3.4 1.6 0.2]
 [4.9 3.1 1.5 0.1]
 [4.6 3.2 1.4 0.2]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.4 2.9 1.4 0.2]
 [4.5 2.3 1.3 0.3]
 [5.1 3.5 1.4 0.3]
 [5.1 3.4 1.5 0.2]
 [4.8 3.  1.4 0.1]
 [5.  3.6 1.4 0.2]
 [4.6 3.4 1.4 0.3]
 [5.4 3.9 1.7 0.4]
 [4.6 3.1 1.5 0.2]
 [5.7 3.8 1.7 0.3]
 [4.9 3.1 1.5 0.1]
 [5.4 3.4 1.7 0.2]
 [5.5 4.2 1.4 0.2]
 [5.7 4.4 1.5 0.4]
 [5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [5.5 3.5 1.3 0.2]
 [4.8 3.4 1.9 0.2]
 [4.3 3.  1.1 0.1]
 [5.  3.4 1.6 0.4]
 [4.7 3.2 1.3 0.2]
 [4.7 3.2 1.6 0.2]
 [5.2 3.4 1.4 0.2]
 [5.1 3.8 1.6 0.2]
 [6.7 3.  5.  1.7]
 [6.3 2.3 4.4 1.3]
 [6.3 2.5 4.9 1.5]
 [5.5 2.4 3.7 1. ]
 [7.  3.2 4.7 1.4]
 [5.6 2.5 3.9 1.1]
 [5.9 3.  4.2 1.5]
 [5.5 2.6 4.4 1.2]
 [6.8 2.8 4.8 1.4]
 [6.2 2.9 4.3 1.3]
 [6.1 2.8 4.  1.3]
 [5.7 2.9 4.2 1.3]
 [6.3 3.3 4.7 1.6]
 [5.  2.3 3.3 1. ]
 [6.1 2.9 4.7 1.4]
 [5.2 2.7 3.9 1.4]
 [6.7 3.1 4.7 1.5]
 [5.5 2.4 3.

In [476]:
# Formating the data to fit on the functions above
y_test = test_data['Species'].values
X_test = test_data
del X_test['Species']
X_test = X_test.values

In [477]:
print(X_test)
print(y_test)

[[4.8 3.1 1.6 0.2]
 [5.4 3.9 1.3 0.4]
 [5.2 3.5 1.5 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.5 0.3]
 [5.3 3.7 1.5 0.2]
 [5.1 3.7 1.5 0.4]
 [5.  3.3 1.4 0.2]
 [5.4 3.7 1.5 0.2]
 [4.4 3.2 1.3 0.2]
 [5.  3.2 1.2 0.2]
 [5.  3.4 1.5 0.2]
 [5.1 3.8 1.9 0.4]
 [5.8 4.  1.2 0.2]
 [4.9 3.1 1.5 0.1]
 [6.2 2.2 4.5 1.5]
 [6.1 2.8 4.7 1.2]
 [5.6 2.7 4.2 1.3]
 [6.6 3.  4.4 1.4]
 [5.  2.  3.5 1. ]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [5.7 2.8 4.1 1.3]
 [6.  2.9 4.5 1.5]
 [6.7 3.1 4.4 1.4]
 [5.6 2.9 3.6 1.3]
 [6.  3.4 4.5 1.6]
 [5.1 2.5 3.  1.1]
 [5.7 2.6 3.5 1. ]
 [6.5 2.8 4.6 1.5]
 [6.8 3.2 5.9 2.3]
 [6.  3.  4.8 1.8]
 [6.9 3.1 5.1 2.3]
 [6.7 3.3 5.7 2.1]
 [6.5 3.  5.5 1.8]
 [6.2 3.4 5.4 2.3]
 [7.2 3.2 6.  1.8]
 [6.4 2.8 5.6 2.2]
 [6.3 3.4 5.6 2.4]
 [6.4 3.1 5.5 1.8]
 [6.4 2.8 5.6 2.1]
 [6.3 2.5 5.  1.9]
 [7.6 3.  6.6 2.1]
 [5.8 2.7 5.1 1.9]
 [5.7 2.5 5.  2. ]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 '

## Para K = 3


In [478]:
k = 3
y_pred = []
for q in X_test :
    y_pred.append(predict_classification(X_train, y_train, q, k))
print(y_pred)

['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica']


In [479]:
# acuracy
print("Acuracy: {}%".format(np.sum(y_pred == y_test) * 100 / y_test.shape[0]))

Acuracy: 97.77777777777777%


## Para K = 5

In [480]:
k = 5
y_pred = []
for q in X_test :
    y_pred.append(predict_classification(X_train, y_train, q, k))
print(y_pred)

['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica']


In [481]:
# acuracy
print("Acuracy: {}%".format(np.sum(y_pred == y_test) * 100 / y_test.shape[0]))

Acuracy: 95.55555555555556%
