In [217]:
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [218]:
# importando o dicionário
iris_data = sklearn.datasets.load_iris()

In [219]:
# importando os dados e os targets
X, y = sklearn.datasets.load_iris(return_X_y=True)
X.shape

(150, 4)

In [220]:
y.shape

(150,)

In [221]:
# separando os dados aleatoriamente em 80%/20%
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.9, random_state=42, stratify=y)

In [222]:
np.sum(y_treino == 0), np.sum(y_treino == 1), np.sum(y_treino == 2)

(5, 5, 5)

In [223]:
np.sum(y_teste == 0), np.sum(y_teste == 1), np.sum(y_teste == 2)

(45, 45, 45)

In [224]:
print(y_treino)
print(y_teste)

[1 1 0 1 0 2 0 2 1 0 1 0 2 2 2]
[0 0 0 0 1 0 1 2 0 2 1 0 0 1 0 0 0 1 0 0 2 1 1 2 1 2 1 2 0 2 1 0 2 1 1 2 1
 1 0 2 0 0 0 2 1 1 1 0 2 0 0 0 2 0 2 1 1 1 0 1 0 1 1 0 2 1 0 0 2 0 0 2 1 1
 2 2 2 2 1 2 0 2 1 1 1 2 1 1 2 0 0 0 2 1 2 1 1 2 0 1 1 0 2 1 2 0 2 0 2 1 1
 2 0 2 1 2 2 0 0 2 2 2 1 2 2 2 1 1 0 1 0 2 2 0 2]


In [225]:
# criando o modelo kNN
modelo_kNN = KNeighborsClassifier(n_neighbors=3) 

In [226]:
# treinando o modelo
modelo_kNN.fit(X_treino, y_treino)

KNeighborsClassifier(n_neighbors=3)

In [227]:
# prevendo os valores ara os dados de teste
y_pred = modelo_kNN.predict(X_teste)
y_pred

array([0, 0, 0, 0, 1, 0, 1, 2, 0, 2, 2, 0, 0, 1, 0, 0, 0, 1, 0, 0, 2, 2,
       1, 2, 1, 2, 1, 2, 0, 2, 1, 0, 2, 1, 1, 2, 1, 1, 0, 2, 0, 0, 0, 2,
       1, 1, 2, 0, 2, 0, 0, 0, 2, 0, 2, 1, 2, 1, 0, 1, 0, 1, 1, 0, 2, 2,
       0, 0, 2, 0, 0, 2, 1, 1, 2, 2, 2, 2, 1, 2, 0, 1, 2, 2, 1, 2, 1, 1,
       2, 0, 0, 0, 2, 1, 2, 1, 1, 2, 0, 1, 1, 0, 2, 1, 2, 0, 2, 0, 2, 1,
       2, 2, 0, 2, 1, 2, 2, 0, 0, 2, 2, 2, 1, 2, 2, 2, 1, 1, 0, 1, 0, 2,
       2, 0, 2])

In [231]:
y_pred == y_teste

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [229]:
# acurácia
print("Acurácia de {}%".format(np.sum(y_pred == y_teste) * 100 / y_teste.shape[0]))

Acurácia de 93.33333333333333%
